# Generated by Django 4.2.6 on 2023-10-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.CharField(max_length=200)),
                ('game_date_time', models.CharField(max_length=200)),
                ('team_away', models.CharField(max_length=200)),
                ('team_home', models.CharField(max_length=200)),
                ('spread_away', models.CharField(max_length=10)),
                ('spread_away_payout', models.CharField(max_length=10)),
                ('spread_home', models.CharField(max_length=10)),
                ('spread_home_payout', models.CharField(max_length=10)),
                ('total_points_away', models.CharField(max_length=10)),
                ('total_points_away_payout', models.CharField(max_length=10)),
                ('total_points_home', models.CharField(max_length=10)),
                ('total_points_home_payout', models.CharField(max_length=10)),
                ('money_line_away', models.CharField(max_length=10)),
                ('money_line_home', models.CharField(max_length=10)),
            ],
        ),
    ]
